# Generated by Django 3.2.8 on 2021-10-23 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officehoursplus', '0003_auto_20211023_1302'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classonlineusers',
            unique_together=set(),
        ),
    ]
