# Generated by Django 3.2.8 on 2021-10-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officehoursplus', '0007_auto_20211023_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classuserstatus',
            name='time_left',
            field=models.DateTimeField(null=True),
        ),
    ]
