# Generated by Django 3.2.8 on 2021-10-23 17:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('officehoursplus', '0004_alter_classonlineusers_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermentorassociations',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
