# Generated by Django 3.2.8 on 2021-10-23 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('officehoursplus', '0008_alter_classuserstatus_time_left'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time_started', models.DateTimeField(auto_now_add=True)),
                ('time_ended', models.DateTimeField(null=True)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='officehoursplus.classes')),
            ],
        ),
        migrations.CreateModel(
            name='UserCallAssociations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_joined', models.DateTimeField(auto_now_add=True)),
                ('time_left', models.DateTimeField(null=True)),
                ('call_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='officehoursplus.call')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
